image: node:alpine

stages:
  - test
  - containerize

.testing: &testing
  stage: test
  before_script:
    - npm install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/

unit test:
  <<: *testing
  script:
    - npm run test -- --color

lint:
  <<: *testing
  script:
    - npm run lint

container:
  stage: containerize
  image: docker:latest
  services:
    - docker:dind
  dependencies:
    - build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME .
    - 'if [ -n "$CI_COMMIT_TAG" ]; then
        docker tag "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG";
        docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG";
      elif [ "$CI_BUILD_REF_NAME" = "master" ]; then
        docker tag "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" "$CI_REGISTRY_IMAGE:latest";
        docker push "$CI_REGISTRY_IMAGE:latest";
      else
        docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME;
      fi'
